# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.arrays.limit as module_0


def test_case_0():
    dict_0 = {}
    var_0 = module_0.limit(dict_0)
    dict_1 = {}
    var_1 = module_0.limit(dict_1)
    var_2 = module_0.limit(dict_0)


def test_case_1():
    str_0 = "0"
    var_0 = module_0.limit(str_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bool_0 = False
    str_0 = "-bhwd\tFU;+$<n\\-CtO"
    var_0 = module_0.limit(str_0, str_0)
    module_0.limit(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    int_0 = -270
    list_0 = [int_0, int_0]
    bytes_0 = b"r\x9f\xdd~\x88\xfe"
    list_1 = [list_0, int_0, bytes_0]
    module_0.limit(list_1, list_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    str_0 = "l[0WY8IR@|GM"
    list_0 = [str_0, str_0, str_0, str_0]
    var_0 = module_0.limit(list_0, str_0)
    set_0 = set()
    var_1 = module_0.limit(var_0)
    module_0.limit(str_0, max_lim=set_0)
