# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.arrays.three_sum as module_0
import builtins as module_1


def test_case_0():
    bool_0 = True
    list_0 = [bool_0, bool_0, bool_0, bool_0]
    var_0 = module_0.three_sum(list_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    module_0.three_sum(none_type_0)


def test_case_2():
    bool_0 = False
    list_0 = [bool_0, bool_0, bool_0, bool_0]
    var_0 = module_0.three_sum(list_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    int_0 = -369
    list_0 = [int_0, int_0, int_0]
    var_0 = module_0.three_sum(list_0)
    bool_0 = False
    list_1 = [bool_0, bool_0, bool_0]
    var_1 = module_0.three_sum(list_1)
    var_2 = module_1.object()
    none_type_0 = None
    module_0.three_sum(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    bool_0 = False
    list_0 = [bool_0, bool_0, bool_0, bool_0]
    var_0 = module_0.three_sum(list_0)
    bool_1 = True
    list_1 = [bool_1, bool_1, bool_1, bool_0, bool_1]
    var_1 = module_0.three_sum(list_1)
    module_0.three_sum(bool_0)
