# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.backtrack.letter_combination as module_0
import builtins as module_1


@pytest.mark.xfail(strict=True)
def test_case_0():
    str_0 = ""
    var_0 = module_0.letter_combinations(str_0)
    var_1 = module_0.letter_combinations(str_0)
    var_2 = module_0.letter_combinations(str_0)
    float_0 = -102.38
    module_0.letter_combinations(float_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "j _Kd"
    module_0.letter_combinations(str_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    set_0 = set()
    var_0 = module_0.letter_combinations(set_0)
    var_1 = module_0.letter_combinations(set_0)
    bool_0 = False
    var_2 = module_0.letter_combinations(set_0)
    module_0.letter_combinations(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    str_0 = "5"
    var_0 = module_0.letter_combinations(str_0)
    var_1 = module_0.letter_combinations(str_0)
    var_2 = module_0.letter_combinations(str_0)
    float_0 = -102.38
    module_1.object(*var_1, **float_0)
